### PR TITLE
Make song list responsive

### LINKED ISSUE #11: Make the song list responsive.
The song list break the app in mobile view, so make sure the list stays below the navigation button in mobile view, or for the width below which the list won't fit in the side.

### PR DESCRIPTION
**Pull request by Atharv777**
I have made the list appear at botom of screen in mobile device. fixes #11
Screenshot (296)
s.

### CODE REVIEW

**Comment by nirajacharyaa** [comment]
I have made sure your contribution count. I will have to wait for other assignees work to be able to merge it.

**Comment by IAmTamal** [comment]
Sir you can go ahead and merge it, i will add more detailings to it.

**Comment by nirajacharyaa** [comment]
@IAmTamal Ok good then, make sure files do not conflicts.

**Comment by nirajacharyaa** [comment]
@Atharv777 Don't forget to star the project, Keep contributing to the Opensource.

**Comment by Atharv777** [comment]
Thanks @nirajacharyaa I will definitely star this project

**Pull request merged**
